title: "Your Project Documentation"
description: "Documentation site for GBB AI HLS Factory Prior Auth"
baseurl: "" # Leave empty if deploying at the repository root
url: "https://pablosalvador10.github.io" # Your GitHub Pages URL
theme: minima # You can use the default Jekyll theme
