title: "Your Project Documentation"
description: "Comprehensive documentation for Your Project."
baseurl: "" # Set if deploying to a subpath
url: "https://pablosalvador10.github.io/" # Replace with your GitHub Pages URL
theme: minima # Using the Minima theme for simplicity
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
