name: AZD Infra Preview Test


on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '!**/*.md'
      
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  preview-provision:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install azd
      uses: Azure/setup-azd@ae0f8b5482eeac61e940f447327d84c73beb8b1e # Pin to specific commit hash

    - name: Log in with Azure (Federated Credentials)
      run: |
        azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
      shell: pwsh
      
    - name: Azure CLI Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        
    - name: Preview Infra Changes
      id: provision-preview
      run: |
        azd provision --no-prompt --preview
      shell: pwsh
      env:
        AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
